(define (type-precedent x)
  (cond ((number? x) 1)
    ((symbol? x) 2)
    ((and (pair? x) (eq? (type-of x) 'constant)) 2)
    ((pair? x) 3)
    (else 4)))

(define (list<? l1 l2)
  (cond ((null? l1) (not (null? l2)))
    ((null? l2) #f)
    ((not (equal? (car l1) (car l2)))
      (expr<? (car l1) (car l2)))
    (else (list<? (cdr l1) (cdr l2)))))

(define (expr<? a b)
  (let ((score-a (type-precedent a))
        (score-b (type-precedent b)))
    (cond
      ((< score-a score-b) #t)
      ((> score-a score-b) #f)
      ((number? a) (< a b))
      ((symbol? a) (string<? (symbol->string a) (symbol->string b)))
      ((and (pair? a) (eq? (type-of a) 'constant))
        (string<? (symbol->string (car (type-unwrap a))) (symbol->string (car (type-unwrap b)))))
      ((pair? a)
        (let ((type-a (type-of a))
              (type-b (type-of b)))
          (if (not (eq? type-a type-b))
            (string<? (symbol->string type-a) (symbol->string type-b))
            (list<? (type-unwrap a) (type-unwrap b)))))
      (else #f))))

(define (simplify expr)
  (if (not (pair? expr))
    expr
    (let* ((type (type-of expr))
           (operands (type-unwrap expr))
           (simplified-operands (map simplify operands))
           (simplify-proc (get 'simplify type)))
      (if simplify-proc
        (apply simplify-proc simplified-operands)
        (type-wrap type simplified-operands)))))
