(define (install-symbolic/parse/infix-package)
  (load "lib/symbolic/parse/infix/sum.scm")
  (load "lib/symbolic/parse/infix/sub.scm")
  (load "lib/symbolic/parse/infix/mul.scm")
  (load "lib/symbolic/parse/infix/div.scm")
  (load "lib/symbolic/parse/infix/exp.scm")
  (load "lib/symbolic/parse/infix/log.scm")
  (load "lib/symbolic/parse/infix/ln.scm")

  (install-symbolic/parse/infix/sum-package)
  (install-symbolic/parse/infix/sub-package)
  (install-symbolic/parse/infix/mul-package)
  (install-symbolic/parse/infix/div-package)
  (install-symbolic/parse/infix/exp-package)
  (install-symbolic/parse/infix/log-package)
  (install-symbolic/parse/infix/ln-package)

  (define (lowest-precedence-op expr)
    (let* ((ops (filter (lambda (x) (and (symbol? x) (get 'precedence x))) expr))
           (precs (map (lambda (x) (get 'precedence x)) ops))
           (min-prec (apply min precs)))
      (let* ((min-ops (filter (lambda (op) (= (get 'precedence op) min-prec)) ops))
             (sample-op (car min-ops))
             (associativity (get 'associativity sample-op)))
        (if (eq? associativity 'right)
          (car min-ops)
          (car (reverse min-ops))))))

  (define (get-prefix op expr)
    (let ((associativity (get 'associativity op)))
      (cond
        ((eq? associativity 'right) (take-while (lambda (x) (not (eq? x op))) expr))
        ((eq? associativity 'left) (reverse (cdr (memq op (reverse expr)))))
        (else (error "Unknown associativity for prefix" op)))))

  (define (get-suffix op expr)
    (let ((associativity (get 'associativity op)))
      (cond
        ((eq? associativity 'right) (cdr (memq op expr)))
        ((eq? associativity 'left) (reverse (take-while (lambda (x) (not (eq? x op))) (reverse expr))))
        (else (error "Unknown associativity for suffix" op)))))

  (define (parse-infix expr)
    (cond
      ((null? expr) expr)
      ((number? expr) expr)
      ((symbol? expr)
        (let ((constant-pred (get 'predicate 'constant)))
          (if (and constant-pred (constant-pred expr))
            ((get 'make 'constant) expr)
            expr)))
      ((null? (cdr expr)) (parse-infix (car expr)))
      ((pair? expr)
        (let* ((op (lowest-precedence-op expr))
               (constructor (get 'make op))
               (lhs (parse-infix (get-prefix op expr)))
               (rhs (parse-infix (get-suffix op expr))))
          (if constructor
            (constructor lhs rhs)
            (type-wrap op (list lhs rhs)))))
      (else expr)))

  (define (unparse-infix expr)
    (cond
      ((not (pair? expr)) expr)
      ((eq? (type-of expr) 'constant) (car (type-unwrap expr)))
      ((= (length expr) 3)
        (let ((op (car expr))
              (lhs (cadr expr))
              (rhs (caddr expr)))
          (list (unparse-infix lhs) op (unparse-infix rhs))))
      ((= (length expr) 2)
        (let ((op (car expr))
              (val (cadr expr)))
          (list op (unparse-infix val))))
      (else (map unparse-infix expr))))

  (put 'parser 'infix parse-infix)
  (put 'unparser 'infix unparse-infix)
  'ok)
