(define (bstree-partial pred elts n)
  (if (= n 0)
    (cons (bstree-make-empty pred) elts)
    (let* ((left-size (quotient (- n 1) 2))
           (left-result (bstree-partial pred elts left-size))
           (left-tree (car left-result))
           (non-left-elts (cdr left-result))
           (this-entry (car non-left-elts))
           (right-size (- n (+ left-size 1)))
           (right-result (bstree-partial pred (cdr non-left-elts) right-size))
           (right-tree (car right-result))
           (remaining-elts (cdr right-result)))
      (cons (bstree-node this-entry pred left-tree right-tree) remaining-elts))))

(define (bstree-join x pred left right)
  (bstree-balance (bstree-node x pred left right)))

(define (bstree-split tree k)
  (if (bstree-empty? tree)
    (cons
      (bstree-make-empty (bstree-predicate tree))
      (bstree-make-empty (bstree-predicate tree)))
    (let ((root (bstree-root tree))
          (pred (bstree-predicate tree))
          (left (bstree-left-branch tree))
          (right (bstree-right-branch tree)))
      (cond
        ((equal? k root) (cons left right))
        ((pred k root)
          (let* ((result (bstree-split left k))
                 (small (car result))
                 (big (cdr result)))
            (cons small (bstree-join root pred big right))))
        (else
          (let* ((result (bstree-split right k))
                 (small (car result))
                 (big (cdr result)))
            (cons (bstree-join root pred left small) big)))))))
