(define bstree-tag-symbol 'bstree)
(define bstree-end 'bstree-end)
(define bstree-null-predicate null?)
(define bstree-empty (cons bstree-tag-symbol (cons bstree-null-predicate bstree-end)))

(define (bstree-node val pred left right)
  (let* ((bare-node (if (and (bstree-empty? left) (bstree-empty? right))
                     (cons val bstree-end)
                     (cons val (cons left right))))
         (node (cons 'bstree (cons pred bare-node))))
    (bstree-set-height node (+ 1 (max (bstree-height left) (bstree-height right))))
    node))
