(load "lib/math.scm")

(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))

(define (start-prime-test n start-time)
  (if (fermat-prime? n 1)
    (report-prime n (- (runtime) start-time))))

(define (report-prime n elapsed-time)
  (display " *** ")
  (if (prime? n)
    (display "True prime found: ")
    (display "False prime found: "))
  (display n)
  (newline)
  (display elapsed-time)
  (newline))

(define (search-for-primes i n)
  (define (iter i n acc)
    (cond
      ((zero? n) acc)
      ((fermat-prime? i 1) (timed-prime-test i) (iter (+ i 2) (- n 1) (cons i acc)))
      (else (iter (+ i 2) n acc))))

  (iter i n '()))

(display "--- First 3 primes >1000 ---")
(newline)
(display (search-for-primes 1001 3))
(newline)
(newline)
(display "--- First 3 primes >10000 ---")
(newline)
(display (search-for-primes 10001 3))
(newline)
(newline)
(display "--- First 3 primes >100000 ---")
(newline)
(display (search-for-primes 100001 3))
(newline)
(newline)
(display "--- First 3 primes >1000000 ---")
(newline)
(display (search-for-primes 1000001 3))
(newline)
(newline)
