(#%require (prefix racket: racket/base))
(load "lib/functools.scm")
(load "lib/sort.scm")
(load "lib/bstree/accessors.scm")
(load "lib/bstree/assemblers.scm")
(load "lib/bstree/balance.scm")
(load "lib/bstree/bstree.scm")
(load "lib/bstree/constructors.scm")
(load "lib/bstree/height.scm")
(load "lib/bstree/merge.scm")
(load "lib/bstree/operations.scm")
(load "lib/bstree/predicates.scm")
(load "lib/bstree/rotations.scm")
