(load "lib/safe-load.scm")
(load "lib/bstree.scm")
(load "lib/functools/enumerate.scm")
(load "lib/functools/filter.scm")
(load "lib/functools/accumulate.scm")
(load "lib/functools/map.scm")
(load "lib/functools/combinatorics.scm")
