(load "lib/math/constants.scm")
(load "lib/math/predicates.scm")
(load "lib/math/arithmetic.scm")
(load "lib/math/factorisation.scm")
(load "lib/math/roots.scm")
(load "lib/math/series.scm")
(load "lib/math/calculus.scm")
(load "lib/math/solvers.scm")
