(load "lib/safe-load.scm")
(load "lib/functools.scm")
(load "lib/typing.scm")
(load "lib/generic-dispatch.scm")
(load "lib/builtin-dispatch.scm")

(load "lib/symbolic/generic.scm")
(load "lib/symbolic/parse.scm")
(load "lib/symbolic/simplify.scm")
(load "lib/symbolic/calculus.scm")
