(define (install-symbolic/algebra-package)
  (load "lib/symbolic/algebra/sum.scm")
  (load "lib/symbolic/algebra/sub.scm")
  (load "lib/symbolic/algebra/mul.scm")
  (load "lib/symbolic/algebra/div.scm")
  (load "lib/symbolic/algebra/exp.scm")
  (load "lib/symbolic/algebra/log.scm")
  (load "lib/symbolic/algebra/ln.scm")

  (install-symbolic/algebra/sum-package)
  (install-symbolic/algebra/sub-package)
  (install-symbolic/algebra/mul-package)
  (install-symbolic/algebra/div-package)
  (install-symbolic/algebra/exp-package)
  (install-symbolic/algebra/log-package)
  (install-symbolic/algebra/ln-package)
  'ok)

(load "lib/symbolic/algebra/generic.scm")
