(define (install-symbolic/calculus-package)
  (load "lib/symbolic/calculus/constant.scm")
  (load "lib/symbolic/calculus/sum.scm")
  (load "lib/symbolic/calculus/sub.scm")
  (load "lib/symbolic/calculus/mul.scm")
  (load "lib/symbolic/calculus/div.scm")
  (load "lib/symbolic/calculus/ln.scm")
  (load "lib/symbolic/calculus/exp.scm")
  (load "lib/symbolic/calculus/log.scm")

  (install-symbolic/calculus/constant-package)
  (install-symbolic/calculus/sum-package)
  (install-symbolic/calculus/sub-package)
  (install-symbolic/calculus/mul-package)
  (install-symbolic/calculus/div-package)
  (install-symbolic/calculus/ln-package)
  (install-symbolic/calculus/exp-package)
  (install-symbolic/calculus/log-package)
  'ok)

(load "lib/symbolic/calculus/generic.scm")
