(load "lib/symbolic/calculus/generic.scm")
(load "lib/symbolic/calculus/sum.scm")
(load "lib/symbolic/calculus/sub.scm")
(load "lib/symbolic/calculus/mul.scm")
(load "lib/symbolic/calculus/div.scm")
(load "lib/symbolic/calculus/ln.scm")
(load "lib/symbolic/calculus/exp.scm")
(load "lib/symbolic/calculus/log.scm")

(install-sum-package)
(install-sub-package)
(install-mul-package)
(install-div-package)
(install-ln-package)
(install-exp-package)
(install-log-package)
