(load "lib/symbolic/parse/generic.scm")
(load "lib/symbolic/parse/sum.scm")
(load "lib/symbolic/parse/sub.scm")
(load "lib/symbolic/parse/mul.scm")
(load "lib/symbolic/parse/div.scm")
(load "lib/symbolic/parse/exp.scm")
(load "lib/symbolic/parse/log.scm")
(load "lib/symbolic/parse/ln.scm")

(install-sum-package)
(install-sub-package)
(install-mul-package)
(install-div-package)
(install-exp-package)
(install-log-package)
(install-ln-package)
