(define (install-symbolic/parse-package)
  (load "lib/symbolic/parse/sum.scm")
  (load "lib/symbolic/parse/sub.scm")
  (load "lib/symbolic/parse/mul.scm")
  (load "lib/symbolic/parse/div.scm")
  (load "lib/symbolic/parse/exp.scm")
  (load "lib/symbolic/parse/log.scm")
  (load "lib/symbolic/parse/ln.scm")

  (install-symbolic/parse/sum-package)
  (install-symbolic/parse/sub-package)
  (install-symbolic/parse/mul-package)
  (install-symbolic/parse/div-package)
  (install-symbolic/parse/exp-package)
  (install-symbolic/parse/log-package)
  (install-symbolic/parse/ln-package)
  'ok)

(load "lib/symbolic/parse/generic.scm")
