(define (install-symbolic/simplify-package)
  (load "lib/symbolic/simplify/sum.scm")
  (load "lib/symbolic/simplify/sub.scm")
  (load "lib/symbolic/simplify/mul.scm")
  (load "lib/symbolic/simplify/div.scm")
  (load "lib/symbolic/simplify/exp.scm")
  (load "lib/symbolic/simplify/log.scm")
  (load "lib/symbolic/simplify/ln.scm")

  (install-symbolic/simplify/sum-package)
  (install-symbolic/simplify/sub-package)
  (install-symbolic/simplify/mul-package)
  (install-symbolic/simplify/div-package)
  (install-symbolic/simplify/exp-package)
  (install-symbolic/simplify/log-package)
  (install-symbolic/simplify/ln-package)
  'ok)

(load "lib/symbolic/simplify/generic.scm")
