(load "lib/symbolic/simplify/generic.scm")
(load "lib/symbolic/simplify/sum.scm")
(load "lib/symbolic/simplify/sub.scm")
(load "lib/symbolic/simplify/mul.scm")
(load "lib/symbolic/simplify/div.scm")
(load "lib/symbolic/simplify/exp.scm")
(load "lib/symbolic/simplify/log.scm")
(load "lib/symbolic/simplify/ln.scm")

(install-sum-package)
(install-sub-package)
(install-mul-package)
(install-div-package)
(install-exp-package)
(install-log-package)
(install-ln-package)
