(define (sort2 l pred)
  (let ((x (car l))
        (y (cadr l)))
    (if (pred x y) l (cons y (cons x '())))))

(define (sort3 l pred)
  (let ((x (car l))
        (y (cadr l))
        (z (caddr l)))
    (if (pred x y)
      (if (pred y z)
        l
        (if (pred x z)
          (list x z y)
          (list z x y)))
      (if (pred x z)
        (list y x z)
        (if (pred y z)
          (list y z x)
          (list z y x))))))
