(load "exercise2/exercise2_56.scm")

(define test-expr1 '(+ x 3))
(define test-expr2 '(* x y))
(define test-expr3 '(* (* x y) (+ x 3)))

(define result-expr1 (deriv test-expr1 'x))
(define result-expr2 (deriv test-expr2 'x))
(define result-expr3 (deriv test-expr3 'x))

(newline)
(display "~~~ Original Implementation ~~~")
(newline)
(display test-expr1)
(display " => ")
(display result-expr1)
(newline)
(display test-expr2)
(display " => ")
(display result-expr2)
(newline)
(display test-expr3)
(display " => ")
(display result-expr3)
(newline)
(newline)
(newline)

(define (variadic-arg-selector s)
  (if (algebraic-op? s)
    (lambda (l)
      (let ((lt (cddr l))
            (lth (caddr l))
            (ltt (cdddr l)))
        (if (null? ltt) lth (cons s lt))))
    (error "Cannot create variadic argument selector for a non algebraic symbol")))

(define augend (variadic-arg-selector '+))
(define multiplicand (variadic-arg-selector '*))

(define test-expr4 '(+ x y 3))
(define test-expr5 '(* x y 3))
(define test-expr6 '(* x y (+ x y 3)))

(define result-expr1 (deriv test-expr1 'x))
(define result-expr2 (deriv test-expr2 'x))
(define result-expr3 (deriv test-expr3 'x))
(define result-expr4 (deriv test-expr4 'x))
(define result-expr5 (deriv test-expr5 'x))
(define result-expr6 (deriv test-expr6 'x))

(display "~~~ New Implementation ~~~")
(newline)
(display test-expr1)
(display " => ")
(display result-expr1)
(newline)
(display test-expr2)
(display " => ")
(display result-expr2)
(newline)
(display test-expr3)
(display " => ")
(display result-expr3)
(newline)
(display test-expr4)
(display " => ")
(display result-expr4)
(newline)
(display test-expr5)
(display " => ")
(display result-expr5)
(newline)
(display test-expr6)
(display " => ")
(display result-expr6)
(newline)
(newline)
